[package]
name = "vent-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-runtime = { path = "../vent-runtime"}
vent-common = { path = "../vent-common"}

# egui
egui = "0.22.0"
egui_dock = "0.8.2"

winit = "0.28.6"
wgpu = "0.16.2"
pollster = "0.3.0"

log = "0.4"

rfd = { version="0.12.0",  default-features = false, features = ["xdg-portal"]}

[target.'cfg(any(not(target_arch = "wasm32"), target_os = "emscripten"))'.dependencies]
simple_logger = "4.2.0"
