[package]
name = "vent-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-common = { path = "../vent-common"}
vent-assets = { path = "../vent-assets" }
vent-ecs = { path = "../vent-ecs"}

winit = "0.29.3"
wgpu = "0.16.2"
pollster = "0.3.0"
log = "0.4"

glam = "0.24.1"
bytemuck = { version = "1.14.0", features = ["derive"] }
downcast-rs = "1.2.0"

# egui
egui = "0.22.0"
egui-wgpu = "0.22.0"
egui-winit = "0.22.0"

[target.'cfg(any(not(target_arch = "wasm32"), target_os = "emscripten"))'.dependencies]
simple_logger = "4.2.0"


[build-dependencies]
fs_extra = "1.3.0"
anyhow = "1.0"
