[package]
name = "vent-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-common = { path = "../vent-common"}
vent-assets = { path = "../vent-assets" }
vent-ecs = { path = "../vent-ecs"}

winit = "0.28.6"
wgpu = "0.16.3"
pollster = "0.3.0"

log = "0.4"

glam = "0.24.1"
bytemuck = { version = "1.13.1", features = ["derive"] }

[target.'cfg(any(not(target_arch = "wasm32"), target_os = "emscripten"))'.dependencies]
simple_logger = "4.2.0"
